### ISSUE TITLE
Aliases get processed during alias commands

### ISSUE THREAD

**Issue by zpatrick** [zpatrick/slackbot#4]
We should have the alias behavior avoid processing aliases when users are using the alias command.
Otherwise, it's impossible to run `!alias rm`:
```
u: !alias add ping "echo pong"
b: Entry *ping* has been added
u: !alias rm ping
b: No entry for *echo* exists
```

**Comment by zpatrick** [comment]
one solution may be to take a `shouldProcess func(m *slack.MessageEvent) bool` as a parameter so users can determine when to process aliases or not:
```
slackbot.NewAliasCommand(store, func(m *slack.MessageEvent) bool {
    return !strings.HasPrefix(m.Text, "slackbot alias")
})
```

**Comment by nehayward** [comment]
Should we add a unit test for this too?
